export const books = [
    {
      id: 1,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqgwtbIlNXd9aGqzGOecq5McSxOIObTQBZIg&s",
      description: "A novel about the American dream and the roaring 1920s.",
      rating: 4.4,
      category: "Fiction",
    },
    {
      id: 2,
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      coverImage: "https://m.media-amazon.com/images/I/811NqsxadrS._AC_UF1000,1000_QL80_.jpg",
      description: "A story of racial injustice and moral growth in the Deep South.",
      rating: 4.9,
      category: "Fiction",
    },
    {
      id: 3,
      title: "Sapiens: A Brief History",
      author: "Yuval Noah Harari",
      coverImage: "https://m.media-amazon.com/images/I/61i4k7DWNFL._AC_UF1000,1000_QL80_.jpg",
      description: "An exploration of humanity’s history, from ancient to modern times.",
      rating: 4.6,
      category: "Non-Fiction",
    },
    {
      id: 4,
      title: "Dune",
      author: "Frank Herbert",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUf-tjQEkBT6dcqMMFe-wzFCwX6qrDNRxXgQ&s",
      description: "A science fiction epic set on the desert planet Arrakis.",
      rating: 4.8,
      category: "Sci-Fi",
    },
    {
      id: 5,
      title: "1984",
      author: "George Orwell",
      coverImage: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
      description: "A dystopian novel about a totalitarian regime and surveillance.",
      rating: 4.9,
      category: "Fiction",
    },
    {
      id: 6,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      coverImage: "https://rukminim2.flixcart.com/image/850/1000/kkec4280/book/d/h/d/pride-prejudice-original-imafzra6pfewjjwb.jpeg?q=90&crop=false",
      description: "A romantic novel about the manners and matrimony of Regency England.",
      rating: 4.8,
      category: "Romance",
    },
    {
      id: 7,
      title: "Becoming",
      author: "Michelle Obama",
      coverImage: "https://m.media-amazon.com/images/I/81h2gWPTYJL.jpg",
      description: "The memoir of former First Lady Michelle Obama.",
      rating: 4.9,
      category: "Memoir",
    },
    {
      id: 8,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      coverImage: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg",
      description: "A story of teenage rebellion and self-discovery.",
      rating: 4.3,
      category: "Fiction",
    },
    {
      id: 9,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      coverImage: "https://m.media-amazon.com/images/I/81t2CVWEsUL.jpg",
      description: "A fantasy adventure preceding the events of The Lord of the Rings.",
      rating: 4.9,
      category: "Fantasy",
    },
    {
      id: 10,
      title: "The Power of Habit",
      author: "Charles Duhigg",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_9Uuq_ob-5Ro-HwAsRNkvQ9qVM8Y-DyfKQA&s",
      description: "An analysis of the science behind habits and how to change them.",
      rating: 4.5,
      category: "Self-Help",
    },
    {
      id: 11,
      title: "The Alchemist",
      author: "Paulo Coelho",
      coverImage: "https://m.media-amazon.com/images/I/71aFt4+OTOL.jpg",
      description: "A philosophical tale about following your dreams.",
      rating: 4.6,
      category: "Fiction",
    },
    {
      id: 12,
      title: "Educated",
      author: "Tara Westover",
      coverImage: "https://m.media-amazon.com/images/I/81WojUxbbFL.jpg",
      description: "A memoir about overcoming a survivalist upbringing to pursue education.",
      rating: 4.7,
      category: "Memoir",
    },
    {
      id: 13,
      title: "Brave New World",
      author: "Aldous Huxley",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_9ldufqwDGdDDw21NnWVKM2i0FyATy_asmw&s",
      description: "A dystopian novel about a genetically engineered future society.",
      rating: 4.6,
      category: "Sci-Fi",
    },
    {
      id: 14,
      title: "The Subtle Art of Not Giving a F*ck",
      author: "Mark Manson",
      coverImage: "https://m.media-amazon.com/images/I/71QKQ9mwV7L.jpg",
      description: "A counterintuitive approach to living a good life.",
      rating: 4.4,
      category: "Self-Help",
    },
    {
      id: 15,
      title: "Atomic Habits",
      author: "James Clear",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7dcjRLk37EwLeYsKMZelbT0yrQplYv4zqIA&s",
      description: "A guide to building good habits and breaking bad ones.",
      rating: 4.8,
      category: "Self-Help",
    },
    {
      id: 16,
      title: "The Road",
      author: "Cormac McCarthy",
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcEl-pr09w3FYIXQyAE0OQYn1INlCCNcpfZQ&s",
      description: "A post-apocalyptic tale of survival and love between a father and son.",
      rating: 4.3,
    category: "Fiction",
  },
  {
    id: 17,
    title: "Little Women",
    author: "Louisa May Alcott",
    coverImage: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781534462205/little-women-9781534462205_hr.jpg",
    description: "A coming-of-age story about the lives of four sisters.",
    rating: 4.7,
    category: "Fiction",
  },
  {
    id: 18,
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    coverImage: "https://rukminim2.flixcart.com/image/850/1000/kit6hzk0-0/book/b/l/g/the-girl-on-the-train-movie-tie-in-original-imafyguxfmzevngg.jpeg?q=20&crop=false",
    description: "A psychological thriller about a woman entangled in a crime.",
    rating: 4.1,
    category: "Thriller",
  },
  {
    id: 19,
    title: "The Book Thief",
    author: "Markus Zusak",
    coverImage: "https://m.media-amazon.com/images/I/81WcnNQ-TBL.jpg",
    description: "A story of a young girl in Nazi Germany who finds solace in books.",
    rating: 4.9,
    category: "Fiction",
  },
  {
    id: 20,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    coverImage: "https://m.media-amazon.com/images/I/81-QB7nDh4L.jpg",
    description: "A classic guide to achieving financial success.",
    rating: 4.5,
    category: "Self-Help",
  },
];
  

   
  